name: karami_app
description: A HRM Chat Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # GraphQL
  graphql_flutter: ^5.1.2
  graphql: ^5.1.1
  web_socket_channel: ^3.0.3
  gql: ^1.0.1

  
  # HTTP & Networking
  http: ^1.1.0
  
  # Local Storage
  hive_flutter: ^1.1.0
  
  # UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  image_picker: ^1.0.4
  file_picker: ^10.3.8
  mime: ^1.0.4
  path_provider: ^2.0.15
  
  # Forms & Validation
  form_validator: ^2.1.1
  
  # Animations
  animations: ^2.0.7
  
  # Utilities
  uuid: ^4.5.2
  connectivity_plus: ^3.0.6
  share_plus: ^7.0.2
  emoji_picker_flutter: ^2.0.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
#   assets:
#     - assets/
  
#   fonts:
#     - family: Roboto
#       fonts:
#         - asset: fonts/Roboto-Regular.ttf
#         - asset: fonts/Roboto-Medium.ttf
#           weight: 500
#         - asset: fonts/Roboto-Bold.ttf
#           weight: 700